[general]
import = [
".config/alacritty/themes/themes/github_dark.toml"
]

[cursor]
style = { shape = "Block", blinking = "Always" }

[window]
padding = { x = 4, y = 2 }
opacity = 0.95

[font]
size = 18.0
normal = { family = "MonoLisa", style = "Regular"  }

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
