[general]
import = [
".config/alacritty/dracula-pro-alucard.toml",
".config/alacritty/dracula-pro-pro.toml",
]

[cursor]
style = { shape = "Block", blinking = "Always" }

[window]
padding = { x = 4, y = 2 }
opacity = 0.95

[font]
size = 17.0
normal = { family = "MonoLisa", style = "Regular"  }
