cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "heroku/brew"

brew "autojump"
brew "bat"
brew "exercism"
brew "git"
brew "gnupg"
brew "hub"
brew "imagemagick"
brew "node"
brew "nodenv"
brew "pinentry-mac"
brew "rbenv"
brew "ruby-build"
brew "tree"
brew "vim"
brew "yarn"

cask "appcleaner"
cask "bartender"
cask "bettertouchtool"
cask "caffeine"
cask "google-chrome"
cask "imageoptim"
cask "intellij-idea"
cask "iterm2"
cask "nordvpn"
cask "postman"
cask "sequel-pro"
cask "slack"
cask "spectacle"
cask "spotify"
cask "sublime-merge"
cask "visual-studio-code"
