cask_args appdir: "/Applications"

brew "asdf"
brew "autojump"
brew "bat"
brew "direnv"
brew "exercism"
brew "gh"
brew "git"
brew "imagemagick"
brew "tree"
brew "neovim"

cask "appcleaner"
cask "brave-browser"
cask "bruno"
cask "cursor"
cask "discord"
cask "imageoptim"
cask "iterm2"
cask "rectangle"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "whatsapp"
